package:
  name: moshpit
  version: {{ PLUGIN_VERSION }}
source:
  path: ..
build:
  script: make install
  entry_points:
    - mosh=moshpit.__main__:mosh
requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools
    - versioningit
    - wheel
  run:
    - python {{ python }}
    - pip
    - click {{ click }}
    - qiime2 >={{ qiime2 }}
    - q2cli >={{ q2cli }}
  build:
  - python {{ python }}
  - setuptools
  - versioningit
test:
  requires:
    - qiime2 >={{ qiime2 }}
    - pytest
  imports:
    - moshpit
  commands:
    - mosh --help
about:
  home: https://bokulich-lab.github.io/moshpit-docs/intro.html
  license: BSD-3-Clause
  license_family: BSD
