{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: moshpit
  version: {{ version }}

source:
  path: ../..

build:
  script: make install
  entry_points:
    - mosh=moshpit.__main__:mosh

requirements:
  host:
    - python  {{ python }}
    - setuptools

  run:
    - python  {{ python }}
    - pip
    - click >=8.1
    - qiime2 {{ qiime2_epoch }}.*
    - q2cli {{ qiime2_epoch }}.*

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - pytest

  imports:
    - moshpit

  commands:
    - mosh --help

about:
  home: https://bokulich-lab.github.io/moshpit-docs/intro.html
  license: BSD-3-Clause
  license_family: BSD
